<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Endereco.aspx.cs" Inherits="PUCMINAS.SistemaAcademico.Aplicacao.Endereco" EnableEventValidation="false" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <h2>Gerenciar Endereço</h2>
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="updEndereco" runat="server">
            <ContentTemplate>
                <table class="style1">
                    <tr>
                        <td style="text-align: right">Cep:</td>
                        <td>
                            <asp:TextBox ID="txtCep"
                                runat="server" OnTextChanged="txtCep_TextChanged" AutoPostBack="true"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvCep" runat="server" ControlToValidate="txtCep" ErrorMessage="Cep Obrigatório" ForeColor="Red">*</asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="style2">Endereço</td>
                        <td>
                            <asp:TextBox ID="txtEndereco"
                                runat="server" TextMode="MultiLine" Width="400px" Height="60px"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvEdereco" runat="server" ControlToValidate="txtEndereco" ErrorMessage="Endereço Obrigatório" ForeColor="Red">*</asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>

                        <td style="text-align: right;" colspan="2">
                            <asp:Button ID="btnSalvar" runat="server" Text="Salvar Endereço" OnClick="btnSalvar_Click" />

                        </td>
                    </tr>
                </table>
                <br />
                <p>
                    <asp:GridView ID="GridView1" runat="server"
                        AllowPaging="True" DataKeyNames="EnderecoID,CEP"
                        AllowSorting="True" AutoGenerateDeleteButton="True"
                        OnRowDeleting="GridView1_RowDeleting">
                    </asp:GridView>
                </p>
                <p>
                    <asp:Label ID="Label1" runat="server"
                        Text="  "></asp:Label>
            </ContentTemplate>
        </asp:UpdatePanel>
        <asp:UpdateProgress ID="updateProgress" runat="server">
            <ProgressTemplate>
                <div style="position: fixed; text-align: center; height: 100%; width: 100%; top: 0; right: 0; left: 0; z-index: 9999999; background-color: #f2f2f2; opacity: 0.7;">
                    <asp:Image ID="imgUpdateProgress" runat="server" ImageUrl="~/Images/loading.gif" AlternateText="Loading ..." ToolTip="Loading ..." Style="padding: 10px; position: fixed; top: 45%; left: 50%;" />
                </div>
            </ProgressTemplate>
        </asp:UpdateProgress>
    </form>
</body>
</html>
