//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoObj", Namespace="http://schemas.datacontract.org/2004/07/PUCMINAS.SistemaAcademico.Wcf")]
    [System.SerializableAttribute()]
    public partial class EnderecoObj : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnderecoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EnderecoID {
            get {
                return this.EnderecoIDField;
            }
            set {
                if ((this.EnderecoIDField.Equals(value) != true)) {
                    this.EnderecoIDField = value;
                    this.RaisePropertyChanged("EnderecoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SistemaAcademicoServico.IEndereco")]
    public interface IEndereco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/buscaCep", ReplyAction="http://tempuri.org/IEndereco/buscaCepResponse")]
        string buscaCep(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/buscaCep", ReplyAction="http://tempuri.org/IEndereco/buscaCepResponse")]
        System.Threading.Tasks.Task<string> buscaCepAsync(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/InserirEndereco", ReplyAction="http://tempuri.org/IEndereco/InserirEnderecoResponse")]
        bool InserirEndereco(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/InserirEndereco", ReplyAction="http://tempuri.org/IEndereco/InserirEnderecoResponse")]
        System.Threading.Tasks.Task<bool> InserirEnderecoAsync(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/BuscaTodosEnderecos", ReplyAction="http://tempuri.org/IEndereco/BuscaTodosEnderecosResponse")]
        PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj[] BuscaTodosEnderecos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/BuscaTodosEnderecos", ReplyAction="http://tempuri.org/IEndereco/BuscaTodosEnderecosResponse")]
        System.Threading.Tasks.Task<PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj[]> BuscaTodosEnderecosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/DeletarEndereco", ReplyAction="http://tempuri.org/IEndereco/DeletarEnderecoResponse")]
        bool DeletarEndereco(int idEndereco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/DeletarEndereco", ReplyAction="http://tempuri.org/IEndereco/DeletarEnderecoResponse")]
        System.Threading.Tasks.Task<bool> DeletarEnderecoAsync(int idEndereco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/AtualizarEndereco", ReplyAction="http://tempuri.org/IEndereco/AtualizarEnderecoResponse")]
        bool AtualizarEndereco(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndereco/AtualizarEndereco", ReplyAction="http://tempuri.org/IEndereco/AtualizarEnderecoResponse")]
        System.Threading.Tasks.Task<bool> AtualizarEnderecoAsync(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnderecoChannel : PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.IEndereco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnderecoClient : System.ServiceModel.ClientBase<PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.IEndereco>, PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.IEndereco {
        
        public EnderecoClient() {
        }
        
        public EnderecoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnderecoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnderecoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnderecoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string buscaCep(string cep) {
            return base.Channel.buscaCep(cep);
        }
        
        public System.Threading.Tasks.Task<string> buscaCepAsync(string cep) {
            return base.Channel.buscaCepAsync(cep);
        }
        
        public bool InserirEndereco(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj) {
            return base.Channel.InserirEndereco(obj);
        }
        
        public System.Threading.Tasks.Task<bool> InserirEnderecoAsync(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj) {
            return base.Channel.InserirEnderecoAsync(obj);
        }
        
        public PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj[] BuscaTodosEnderecos() {
            return base.Channel.BuscaTodosEnderecos();
        }
        
        public System.Threading.Tasks.Task<PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj[]> BuscaTodosEnderecosAsync() {
            return base.Channel.BuscaTodosEnderecosAsync();
        }
        
        public bool DeletarEndereco(int idEndereco) {
            return base.Channel.DeletarEndereco(idEndereco);
        }
        
        public System.Threading.Tasks.Task<bool> DeletarEnderecoAsync(int idEndereco) {
            return base.Channel.DeletarEnderecoAsync(idEndereco);
        }
        
        public bool AtualizarEndereco(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj) {
            return base.Channel.AtualizarEndereco(obj);
        }
        
        public System.Threading.Tasks.Task<bool> AtualizarEnderecoAsync(PUCMINAS.SistemaAcademico.Aplicacao.SistemaAcademicoServico.EnderecoObj obj) {
            return base.Channel.AtualizarEnderecoAsync(obj);
        }
    }
}
